name: local_grocery
description: Retail application.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter: #flutter sdk
    sdk: flutter

  get: ^4.6.5 #getx state manager
  dio: ^5.3.2 #network
  dio_http2_adapter: ^2.0.0 #network client adapter
  connectivity: ^3.0.6 #network connectivity check
  json_annotation: ^4.0.1 #json annotation provider
  fast_cached_network_image: ^1.2.0 #image loading
  google_fonts: ^6.2.1 #google fonts
  font_awesome_flutter: ^10.4.0 # icons
  shared_preferences: ^2.0.6 # storage
  file_picker: ^8.0.3 #file_image_picker
  intl_phone_field: ^3.2.0 #international phone field
  flutter_secure_storage: ^9.1.1 #secure storage
  shimmer: ^3.0.0 #loading effect
  byte_converter: ^1.3.0 #convert image size to bytes
  path_provider: ^2.1.1 #for getting the file path
  open_filex: ^4.4.0 # for open attachment
  webview_flutter: ^4.8.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0 


  

dev_dependencies: #dev dependencies
  flutter_native_splash: ^2.0.6+1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  build_runner: ^2.0.5 #generate scripts
  json_serializable: ^6.5.4 #json serializable

flutter_native_splash:
   color: "#ffffff"
   android: true
   ios: true
   web: false
   fullscreen: true



flutter: #external paths and properties
  uses-material-design: true
  assets:
    - assets/images/
    - path: assets/images/dev/
      flavors:
        - dev
    - path: assets/images/prod/
      flavors:
        - prod
    
  fonts:
    - family: Popins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          style: italic
